Repository nodeSolidServer/node-solid-server, pull requests merged in 2018-10, with the labels that each got.

#835 Block cookie auth from non-subdomains, but allow all other auth from everywhere
  lib/create-app.js
  lib/models/solid-host.js
  test/unit/solid-host-test.js
Labels: authentication, blocker, security

#863 Serve front-end assets from node_modules
  common/css/bootstrap.min.css
  common/css/bootstrap.min.css.map
  default-views/account/register-form.hbs
  lib/create-app.js
  package-lock.json
  package.json
Labels: enhancement, ready for merge

#858 Delete account implementation
  default-templates/emails/delete-account.js
  default-templates/new-account/index.html
  default-views/account/account-deleted.hbs
  default-views/account/delete-confirm.hbs
  default-views/account/delete-link-sent.hbs
  default-views/account/delete.hbs
  lib/api/accounts/user-accounts.js
  lib/debug.js
  lib/models/account-manager.js
  lib/models/email-service.js
  lib/models/token-service.js
  lib/requests/delete-account-confirm-request.js
  lib/requests/delete-account-request.js
  lib/requests/password-reset-email-request.js
  package-lock.json
  package.json
  test/unit/account-manager-test.js
  test/unit/delete-account-confirm-request-test.js
  test/unit/delete-account-request-test.js
  test/unit/token-service-test.js
Labels: semver-minor

#872 Make login work on Safari
  lib/api/authn/webid-oidc.js
  lib/utils.js
  package-lock.json
  package.json
  static/popup-redirect.html
Labels: authentication, bug

#871 Align landing page login experience
  default-templates/server/index.html
Labels: UI, authentication, enhancement

#794 Remove solid:inbox.
  test/resources/accounts-acl/config/templates/new-account/profile/card
Labels: bug, ready for review, semver-major
