Repository nodeSolidServer/node-solid-server, pull requests merged in 2018-12, with the labels that each got.

#999 Fix remaining camelCase config names in init.js, Closes #997
  bin/lib/options.js
Labels: bug, in progress, ready for review

#1005 Hide register button when logged in
  common/js/auth-buttons.js
Labels: enhancement, in progress, ready for review

#1006 Fix account settings always being hidden
  common/js/auth-buttons.js
Labels: bug, in progress, ready for review

#1007 Add logout button to login-required view
  default-views/auth/login-required.hbs
Labels: bug, in progress, ready for review

#1010 Fix listings showing extensionless files incorrectly, Closes #1009
  lib/ldp-container.js
  lib/ldp.js
  test/integration/ldp-test.js
Labels: bug, in progress, ready for review

#1014 Make DELETE require write permissions on container
  lib/handlers/allow.js
  lib/ldp-middleware.js
Labels: in progress, ready for review

#1013 Fix server printing stacktrace after logging in, Closes #1000
  lib/handlers/get.js
Labels: bug, in progress, ready for review

#1003 Fix registration from solid-auth-client not redirecting after login
  lib/requests/create-account-request.js
Labels: bug, in progress, ready for review

#1022 Updates to changelog
  CHANGELOG.md
Labels: in progress

#1027 Use http schema for solid terms
  default-templates/new-account/settings/privateTypeIndex.ttl
  default-templates/new-account/settings/publicTypeIndex.ttl
  test/resources/accounts-acl/config/templates/new-account/settings/privateTypeIndex.ttl
  test/resources/accounts-acl/config/templates/new-account/settings/publicTypeIndex.ttl
Labels: in progress

#1028 Fix path-related Windows problems
  lib/handlers/index.js
  lib/header.js
  lib/ldp.js
  lib/resource-mapper.js
  package-lock.json
  package.json
  test/integration/http-test.js
  test/unit/utils-test.js
Labels: in progress

#1034 Add the serverUri as trusted origin for multiuser
  lib/handlers/allow.js
Labels: in progress
