Repository nodeSolidServer/node-solid-server, pull requests merged in 2018-08, with the labels that each got.

#737 Fix logging in with client certificate
  default-views/auth/login-tls.hbs
  default-views/auth/login.hbs
  default-views/auth/select-provider.hbs
  lib/requests/login-request.js
  test/unit/login-request-test.js
Labels: authentication, bug

#742 Restore globbing functionality
  lib/handlers/allow.js
  lib/handlers/get.js
Labels: bug

#740 Add Vary: Accept header
  lib/create-app.js
Labels: in progress

#751 Always log in through the client
  common/js/solid-auth-client.bundle.js
  common/js/solid-auth-client.bundle.js.map
  common/popup.html
  default-views/auth/login-required.hbs
  default-views/auth/no-permission.hbs
  default-views/auth/select-provider.hbs
  lib/api/authn/webid-oidc.js
  lib/handlers/error-pages.js
  package-lock.json
  package.json
  test/integration/authentication-oidc-test.js
  test/integration/errors-oidc-test.js
  test/integration/patch-test.js
  test/resources/accounts-acl/config/views/auth/login-required.hbs
  test/resources/accounts-acl/config/views/auth/select-provider.hbs
  test/unit/error-pages-test.js
Labels: UI, authentication

#752 Add type index references to prefs.ttl
  default-templates/new-account/settings/prefs.ttl
Labels: bug

#750 DevOps changes to integrate snyk.io and email notification
  .snyk
  .travis.yml
  package-lock.json
  package.json
Labels: devops

#759 Warn and log out when OIDC issuer is not set correctly
  default-views/auth/login-required.hbs
  lib/api/authn/webid-oidc.js
  lib/handlers/error-pages.js
Labels: UI, authentication, enhancement

#765 Set strictOrigin by default
  config/defaults.js
Labels: authentication, enhancement

#763 Remove broken apps from homepage
  default-templates/new-account/index.html
Labels: UI

#767 Make entire profile folder public read
  default-templates/new-account/profile/.acl
  default-templates/new-account/profile/card.acl
  test/integration/account-creation-oidc-test.js
Labels: enhancement, semver-major

#768 Use default instead of defaultForNew
  bin/lib/start.js
  default-templates/new-account/.acl
  default-templates/new-account/inbox/.acl
  default-templates/new-account/public/.acl
  default-templates/new-account/settings/.acl
  test/integration/acl-oidc-test.js
  test/integration/acl-tls-test.js
  test/resources/accounts-acl/config/templates/new-account/.acl
  test/resources/accounts-acl/config/templates/new-account/inbox/.acl
  test/resources/accounts-acl/config/templates/new-account/settings/.acl
  test/resources/accounts-acl/tim.localhost/append-inherited/.acl
  test/resources/accounts-acl/tim.localhost/fake-account/.acl
  test/resources/accounts-acl/tim.localhost/group/test-folder/.acl
  test/resources/accounts-acl/tim.localhost/origin/.acl
  test/resources/accounts-acl/tim.localhost/owner-only/.acl
  test/resources/accounts-acl/tim.localhost/write-acl/.acl
  test/resources/accounts-scenario/bob/.acl
  test/resources/accounts/errortests/.acl
  test/resources/accounts/localhost/.acl
  test/resources/accounts/localhost/samplePublicContainer/.acl
  test/resources/accounts/localhost/sampleUser1Container/.acl
  test/resources/accounts/tim.localhost/.acl
  test/resources/acl-tls/append-inherited/.acl
  test/resources/acl-tls/fake-account/.acl
  test/resources/acl-tls/origin/.acl
  test/resources/acl-tls/owner-only/.acl
  test/resources/acl-tls/read-acl/.acl
  test/resources/acl-tls/write-acl/.acl
  test/resources/patch/.acl
Labels: enhancement, semver-major

#769 Use latest solid-auth-client
  default-templates/new-account/index.html
  default-views/auth/login-required.hbs
  lib/api/authn/webid-oidc.js
  package-lock.json
  package.json
Labels: UI, enhancement
