Repository nodeSolidServer/node-solid-server, pull requests merged in 2018-06, with the labels that each got.

#700 Add robots.txt and .acl to default account and server templates
  default-templates/new-account/robots.txt
  default-templates/new-account/robots.txt.acl
  default-templates/server/favicon.ico
  default-templates/server/favicon.ico.acl
  default-templates/server/robots.txt
  default-templates/server/robots.txt.acl
Labels: ready for review

#716 Add .well-known folder and ACL for public access
  default-templates/server/.well-known/.acl
Labels: feature, ready for merge

#715 Make per-origin .well-known folder
  default-templates/new-account/.well-known/.acl
Labels: ready for merge

#717 Set up SonarJS static analysis
  .travis.yml
  bin/lib/options.js
  lib/acl-checker.js
  lib/handlers/get.js
  lib/handlers/post.js
  package-lock.json
  package.json
  test/integration/header-test.js
Labels: devops, ready for review
