Repository nodeSolidServer/node-solid-server, pull requests merged in 2018-11, with the labels that each got.

#893 A simple service for handling blacklisting of usernames
  README.md
  config/usernames-blacklist.json
  lib/create-app.js
  lib/requests/create-account-request.js
  lib/services/blacklist-service.js
  lib/services/email-service.js
  lib/services/token-service.js
  package-lock.json
  package.json
  test/unit/account-manager-test.js
  test/unit/blacklist-service-test.js
  test/unit/create-account-request-test.js
  test/unit/email-service-test.js
  test/unit/email-welcome-test.js
  test/unit/token-service-test.js
Labels: in progress

#888 Add private folder to template
  default-templates/new-account/index.html
  default-templates/new-account/private/.acl
Labels: UI, feature, ready for merge

#912 Found a bug in how value of toc-checkbox is handled
  default-views/account/register-form.hbs
  test/integration/account-creation-oidc-test.js
Labels: in progress

#919 Invalidusernames command
  bin/lib/cli.js
  bin/lib/common.js
  bin/lib/invalidUsernames.js
  bin/lib/options.js
  bin/lib/start.js
  config.json-default
  default-templates/emails/invalid-username.js
  default-views/account/invalid-username.hbs
  lib/common/user-utils.js
  lib/requests/create-account-request.js
  package-lock.json
  package.json
  test/unit/user-utils-test.js
Labels: in progress

#915 Fix failure to log in when requesting binary files
  default-views/auth/login-required.hbs
Labels: authentication, in progress, inrupt-sprint

#917 Polish login-logout
  default-templates/new-account/index.html
  default-templates/server/index.html
Labels: enhancement, in progress

#909 Make --verbose default. Add --silent option.
  README.md
  bin/lib/start.js
Labels: inrupt-sprint

#924 Improvement/invalidusername command
  bin/lib/common.js
  bin/lib/invalidUsernames.js
  bin/lib/start.js
  default-views/account/invalid-username.hbs
Labels: in progress

#848 Add logout button to access denied page
  common/js/auth-buttons.js
  default-templates/new-account/index.html
  default-templates/server/index.html
  default-views/auth/login-required.hbs
  default-views/auth/no-permission.hbs
  package-lock.json
  package.json
Labels: enhancement, in progress, inrupt-sprint, ready for review

#932 Fixes login UI for small popup window sizes
  common/css/solid.css
  default-views/auth/login-username-password.hbs
  default-views/auth/login.hbs
  package-lock.json
Labels: in progress, inrupt-sprint

#911 Code to check quota on backend
  default-templates/new-account/settings/serverSide.ttl
  default-templates/new-account/settings/serverSide.ttl.acl
  lib/debug.js
  lib/handlers/patch.js
  lib/ldp.js
  lib/utils.js
  package-lock.json
  package.json
  test/integration/ldp-test.js
  test/integration/quota-test.js
  test/resources/accounts-acl/config/templates/new-account/settings/serverSide.ttl
  test/resources/accounts-acl/quota/settings/serverSide.ttl
  test/settings/serverSide.ttl
Labels: in progress, inrupt-sprint

#786 Improved tests for integrating acl-check.js
  test/integration/acl-oidc-test.js
  test/integration/authentication-oidc-test.js
  test/resources/accounts-acl/tim.localhost/group/test-folder/.acl
  test/resources/config/defaults.js
Labels: Decision-Needed, in progress, inrupt-sprint

#958 Fix index path creation on Windows
  lib/handlers/index.js
Labels: in progress

#960 Wire up ResourceMapper
  config/defaults.js
  lib/create-app.js
  lib/handlers/copy.js
  lib/handlers/get.js
  lib/handlers/index.js
  lib/handlers/patch.js
  lib/handlers/post.js
  lib/handlers/put.js
  lib/header.js
  lib/ldp-copy.js
  lib/ldp.js
  lib/legacy-resource-mapper.js
  lib/resource-mapper.js
  lib/utils.js
  test/integration/account-manager-test.js
  test/integration/acl-oidc-test.js
  test/integration/acl-tls-test.js
  test/integration/formats-test.js
  test/integration/http-test.js
  test/integration/ldp-test.js
  test/resources/sampleContainer/example4$.ttl
  test/unit/account-manager-test.js
  test/unit/legacy-resource-mapper-test.js
  test/unit/resource-mapper-test.js
  test/unit/user-accounts-api-test.js
  test/unit/utils-test.js
Labels: enhancement, in progress, inrupt-sprint, ready for merge, semver-major

#961 Migrate resources
  bin/lib/cli.js
  bin/lib/migrateLegacyResources.js
  default-templates/new-account/profile/card$.ttl
  test/integration/account-creation-oidc-test.js
  test/integration/account-manager-test.js
  test/integration/account-template-test.js
Labels: feature, in progress, ready for merge, semver-major

#966 Make migration tool also scan through config/templates
  bin/lib/migrateLegacyResources.js
Labels: enhancement, in progress, ready for review

#885 Kebab case CLI Flags
  README.md
  bin/lib/options.js
  test/unit/options.js
Labels: semver-major

#969 Integrate acl check group listings
  lib/acl-checker.js
  lib/handlers/allow.js
  test/integration/acl-oidc-test.js
  test/integration/acl-tls-test.js
  test/integration/authentication-oidc-test.js
  test/resources/accounts-acl/tim.localhost/group/test-folder/.acl
  test/resources/accounts-acl/tim.localhost/group/test-folder/group-listing.ttl
Labels: in progress

#957 Remove old /logout bindings - PR v2
  lib/api/authn/webid-oidc.js
Labels: in progress

#967 Add ResourceMapper changes to 5.0.0 release notes
  CHANGELOG.md
Labels: documentation, in progress, ready for review

#971 Cache npm in Travis
  .travis.yml
Labels: enhancement, in progress, ready for review

#953 Update index.html based on whether meta-tag is set or not
  README.md
  bin/lib/cli-utils.js
  bin/lib/cli.js
  bin/lib/common.js
  bin/lib/invalidUsernames.js
  bin/lib/start.js
  bin/lib/updateIndex.js
  default-templates/new-account/index.html
  lib/common/fs-utils.js
  lib/common/template-utils.js
  lib/common/user-utils.js
  lib/handlers/index.js
  lib/ldp.js
  lib/resource-mapper.js
  lib/utils.js
  package-lock.json
  package.json
  test/resources/accounts-acl/tim.localhost/write-acl/test-file$.txt
  test/resources/acl-tls/write-acl/test-file$.ttl
  test/unit/user-utils-test.js
Labels: in progress

#976 Fix crash when running solid init
  bin/lib/options.js
Labels: bug, in progress

#978 Fix solid-auth-client.bundle.js not being exposed
  lib/create-app.js
Labels: bug, in progress

#980 Fix no logging output appearing when in non-quiet-mode
  bin/lib/start.js
Labels: bug, in progress

#937 Simple RDF validation for ACL files
  lib/handlers/get.js
  lib/handlers/put.js
  lib/ldp.js
  lib/models/account-template.js
  test/integration/cors-proxy-test.js
  test/integration/errors-test.js
  test/integration/formats-test.js
  test/integration/http-test.js
  test/integration/validate-tts.js
  test/resources/invalid1.ttl
  test/resources/invalid2.ttl
  test/utils.js
Labels: in progress

#984 Fix/missing root acl
  default-templates/server/.acl
  lib/handlers/get.js
  lib/server-config.js
  test/integration/account-creation-oidc-test.js
  test/integration/acl-tls-test.js
  test/integration/authentication-oidc-test.js
  test/integration/errors-oidc-test.js
  test/resources/accounts-acl/config/templates/server/.acl
  test/resources/accounts-acl/localhost/.acl
  test/resources/accounts-scenario/alice/.acl-override
  test/resources/accounts-scenario/bob/.acl-override
  test/resources/accounts/errortests/.acl-override
  test/resources/accounts/localhost/.acl
  test/resources/accounts/localhost/api/.acl
  test/resources/headers/.acl
  test/utils.js
Labels: bug, in progress, inrupt-sprint

#990 Made use of aclCheck.configureLogger
  lib/create-app.js
  package-lock.json
  package.json
Labels: in progress
