Repository nodeSolidServer/node-solid-server, pull requests merged in 2018-05, with the labels that each got.

#660 Fix .acl lookup for paths with spaces
  lib/handlers/allow.js
  lib/legacy-resource-mapper.js
  lib/resource-mapper.js
  test/unit/legacy-resource-mapper-test.js
  test/unit/resource-mapper-test.js
Labels: Epic, bug, priority, ready for review, security

#655 Use block level scope instead of function level scope
  lib/api/authn/webid-tls.js
  lib/capability-discovery.js
  lib/create-server.js
  lib/debug.js
  lib/handlers/allow.js
  lib/handlers/delete.js
  lib/handlers/get.js
  lib/handlers/index.js
  lib/handlers/post.js
  lib/handlers/put.js
  lib/header.js
  lib/http-error.js
  lib/ldp-container.js
  lib/ldp-copy.js
  lib/ldp-middleware.js
  lib/ldp.js
  lib/utils.js
Labels: enhancement

#648 Send full returnToUrl to oidc-auth-manager
  default-views/auth/login-tls.hbs
  default-views/auth/select-provider.hbs
  lib/handlers/error-pages.js
Labels: blocker, bug, ready for review

#666 Prevent double slashes in the "service" link header
  lib/handlers/options.js
  test/integration/capability-discovery-test.js
Labels: bug

#669 Only use cookies in HTTPS mode
  lib/create-app.js
Labels: authentication, bug, security
