Repository nodeSolidServer/node-solid-server, pull requests merged in 2018-03, with the labels that each got.

#640 Update databrowser.html to latest mashlib
  static/databrowser.html
Labels: blocker, bug

#613 + command like arg: --config-file [./config.json]
  bin/lib/options.js
  bin/lib/start.js
Labels: config

#642 Drop Node 6 support
  .travis.yml
  package.json
Labels: ready for merge, ready for review

#643 Add ResourceMapper class for URL/file mapping
  lib/resource-mapper.js
  test/unit/resource-mapper-test.js
Labels: enhancement, feature, ready for merge, ready for review
