Repository nodeSolidServer/node-solid-server, pull requests merged in 2019-01, with the labels that each got.

#1043 Improve tests given that origin doesn't matter for public resources
  package-lock.json
  package.json
  test/integration/acl-oidc-test.js
  test/integration/acl-tls-test.js
Labels: in progress

#1051 Fix/singleuser
  lib/models/account-manager.js
  test/integration/account-creation-oidc-test.js
Labels: bug, in progress

#1052 Fix that should create a correct base URI wrt validation when PUTing TTL-files
  lib/handlers/get.js
  lib/handlers/put.js
  lib/resource-mapper.js
Labels: in progress

#1049 Added myself as contributor
  package.json
Labels: in progress

#1054 Add contributors document with sections
  CONTRIBUTORS.md
  EXAMPLES.md
  LICENSE.md
  README.md
  package.json
Labels: documentation, in progress

#1065 Default pod template sets rights on / instead of index.html
  default-templates/new-account/.acl
  default-templates/new-account/index.html.acl
  default-templates/server/index.html.acl
Labels: blocker, bug
